# Generated by Django 6.0.2 on 2026-02-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_books_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='Book',
        ),
    ]
